### ISSUE TITLE
DataTables 1.10.11 TODO

### ISSUE THREAD

**Issue by yihui** [rstudio/DT#245]
- [x] There are more styles, including bootstrap4, material, semanticui, uikit, ...
- [x] Most extensions support different styles now (e.g. AutoFill, Responsive, ...)
- [x] ColVis and TableTools are retired; use Buttons and Select instead
- [x] Use `htmlDependency(all_files = FALSE)` some some dependencies (requires the latest version of htmltools)
- [ ] Are those .extra.css still necessary?
- [ ] Automatically configure extensions
